Repository MakePrisms/agicash, pull requests merged in 2025-05, with the labels that each got.

#307 clean up home page and update tests
  app/routes/_protected._index.tsx
  e2e/helpers.ts
  e2e/login.spec.ts
  e2e/signup.spec.ts
  e2e/verify-email.spec.ts
Labels: enhancement

#367 bug fix: use counter and outputAmounts from quote if set
  app/features/receive/cashu-receive-quote-service.ts
Labels: bug

#402 Fix search bar spinner visibility
  app/components/search-bar.tsx
Labels: codex

#412 Implement username auto-select on edit
  app/features/settings/profile/editable-username.tsx
Labels: codex

#419 Update send/receive swap completion
  supabase/migrations/20250503202924_cashu-send-swaps.sql
Labels: codex

#422 Use camelCase route params
  app/features/settings/accounts/$accountId.tsx
  app/routes/_protected.receive.request.($accountId).tsx
  app/routes/_protected.settings.accounts.$accountId.tsx
  app/routes/_protected.settings.contacts.$contactId.tsx
  app/routes/api.lnurlp.callback.$userId.ts
  app/routes/api.lnurlp.verify.$cashuReceiveQuoteId.ts
Labels: codex

#423 Fix view transition state with programmatic navigation
  app/lib/transitions/view-transition.tsx
Labels: codex
